# Generated by Django 2.1 on 2018-05-13 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='four_num',
        ),
        migrations.RemoveField(
            model_name='task',
            name='tw_num',
        ),
    ]
