# Generated by Django 2.1 on 2018-05-16 06:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20180513_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='add_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='开始时间'),
        ),
        migrations.AddField(
            model_name='task',
            name='algorithm',
            field=models.CharField(default=None, max_length=300),
        ),
        migrations.AddField(
            model_name='task',
            name='end_date',
            field=models.DateTimeField(default=None, verbose_name='结束时间'),
        ),
        migrations.AlterField(
            model_name='task',
            name='already',
            field=models.IntegerField(),
        ),
    ]
