# Generated by Django 2.1 on 2018-05-16 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20180516_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='algorithm',
            field=models.CharField(blank=True, default=None, max_length=300, null=True),
        ),
    ]
