# Generated by Django 2.1 on 2018-05-18 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_dataset'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='Authority',
            field=models.BooleanField(default=False),
        ),
    ]
